// PDF Generation utilities for downloadable resources

export interface WorkoutLogEntry {
  date: string;
  workoutType: string;
  workoutName: string;
  duration: string;
  calories: string;
}

export interface UserProgress {
  totalWorkouts: number;
  totalHours: number;
  currentStreak: number;
  weeklyCompletions: number;
  weeklyGoal: number;
}

export interface UserProfile {
  displayName: string | null;
  fitnessGoal: string | null;
  experienceLevel: string | null;
  height?: number | null;
  weight?: number | null;
}

// Generate Workout Tracker PDF content
export function generateWorkoutTrackerPDF(
  workoutLogs: WorkoutLogEntry[],
  userProfile: UserProfile
): string {
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Workout Tracker - ${date}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; }
    h1 { color: #FF7A00; text-align: center; }
    h2 { color: #333; border-bottom: 2px solid #FF7A00; padding-bottom: 5px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
    th { background-color: #FF7A00; color: white; }
    tr:nth-child(even) { background-color: #f2f2f2; }
    .summary { background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 20px 0; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <h1>🏋️ FitLine-Gym Workout Tracker</h1>
  <div class="summary">
    <h2>User Profile</h2>
    <p><strong>Name:</strong> ${userProfile.displayName || 'Not set'}</p>
    <p><strong>Goal:</strong> ${userProfile.fitnessGoal || 'Not set'}</p>
    <p><strong>Experience:</strong> ${userProfile.experienceLevel || 'Not set'}</p>
    <p><strong>Generated:</strong> ${date}</p>
  </div>
  
  <h2>Workout History</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Workout Type</th>
        <th>Workout Name</th>
        <th>Duration</th>
        <th>Calories</th>
      </tr>
    </thead>
    <tbody>
      ${workoutLogs.length > 0 
        ? workoutLogs.map(log => `
          <tr>
            <td>${log.date}</td>
            <td>${log.workoutType}</td>
            <td>${log.workoutName}</td>
            <td>${log.duration}</td>
            <td>${log.calories}</td>
          </tr>
        `).join('')
        : '<tr><td colspan="5" style="text-align: center;">No workouts logged yet. Start your fitness journey today!</td></tr>'
      }
    </tbody>
  </table>
  
  <div class="footer">
    <p>Generated by FitLine-Gym | Keep pushing your limits! 💪</p>
  </div>
</body>
</html>
  `.trim();
}

// Generate Nutrition Guide PDF content
export function generateNutritionGuidePDF(
  userProfile: UserProfile,
  tdee: number | null
): string {
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  const goal = userProfile.fitnessGoal || 'general';
  const goalText = goal === 'lose-weight' ? 'Weight Loss' :
                   goal === 'build-muscle' ? 'Muscle Gain' :
                   goal === 'improve-endurance' ? 'Endurance' : 'General Fitness';

  const maintenance = tdee || 2000;
  const deficit = maintenance - 500;
  const surplus = maintenance + 300;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Nutrition Guide - ${date}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; }
    h1 { color: #FF7A00; text-align: center; }
    h2 { color: #333; border-bottom: 2px solid #FF7A00; padding-bottom: 5px; }
    .section { margin: 20px 0; padding: 15px; background-color: #f9f9f9; border-radius: 5px; }
    .meal-plan { background-color: white; padding: 15px; margin: 10px 0; border-left: 4px solid #FF7A00; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
    ul { margin: 10px 0; }
    li { margin: 5px 0; }
  </style>
</head>
<body>
  <h1>🥗 FitLine-Gym Nutrition Guide</h1>
  
  <div class="section">
    <h2>Your Profile</h2>
    <p><strong>Name:</strong> ${userProfile.displayName || 'Not set'}</p>
    <p><strong>Fitness Goal:</strong> ${goalText}</p>
    <p><strong>Daily Calorie Needs:</strong> ${maintenance} calories (maintenance)</p>
    ${goal === 'lose-weight' ? `<p><strong>Weight Loss Target:</strong> ${deficit} calories/day</p>` : ''}
    ${goal === 'build-muscle' ? `<p><strong>Muscle Gain Target:</strong> ${surplus} calories/day</p>` : ''}
  </div>

  <div class="section">
    <h2>Daily Meal Plan</h2>
    ${getMealPlanHTML(goal, maintenance, deficit, surplus, userProfile.weight || 70)}
  </div>

  <div class="section">
    <h2>Nutrition Tips</h2>
    <ul>
      <li>Stay hydrated - aim for 8-10 glasses of water daily</li>
      <li>Eat protein with every meal (aim for 1.2-2g per kg body weight)</li>
      <li>Include complex carbs for sustained energy</li>
      <li>Don't skip meals - consistency is key</li>
      <li>Track your intake to stay on target</li>
    </ul>
  </div>

  <div class="footer">
    <p>Generated by FitLine-Gym | ${date}</p>
    <p>Remember: Consult a nutritionist for personalized advice</p>
  </div>
</body>
</html>
  `.trim();
}

function getMealPlanHTML(goal: string, maintenance: number, deficit: number, surplus: number, weight: number): string {
  const protein = Math.round(weight * 1.8);
  
  if (goal === 'lose-weight') {
    return `
      <div class="meal-plan">
        <h3>Breakfast (400 kcal)</h3>
        <ul>
          <li>2 boiled eggs</li>
          <li>1 bowl oats with milk</li>
          <li>1 apple</li>
        </ul>
      </div>
      <div class="meal-plan">
        <h3>Lunch (500 kcal)</h3>
        <ul>
          <li>1 cup brown rice</li>
          <li>Dal (lentils)</li>
          <li>1 cup vegetables</li>
          <li>100g chicken/paneer</li>
        </ul>
      </div>
      <div class="meal-plan">
        <h3>Dinner (350 kcal)</h3>
        <ul>
          <li>1 roti</li>
          <li>Sabzi (vegetables)</li>
          <li>Salad</li>
        </ul>
      </div>
      <div class="meal-plan">
        <h3>Snack (150 kcal)</h3>
        <ul>
          <li>1 apple</li>
          <li>10 almonds</li>
        </ul>
      </div>
      <p><strong>Total: ${deficit} calories/day</strong></p>
    `;
  }
  
  if (goal === 'build-muscle') {
    return `
      <div class="meal-plan">
        <h3>Breakfast (500 kcal, 30g protein)</h3>
        <ul>
          <li>3 eggs</li>
          <li>2 slices bread</li>
          <li>1 banana</li>
        </ul>
      </div>
      <div class="meal-plan">
        <h3>Lunch (650 kcal, 45g protein)</h3>
        <ul>
          <li>1.5 cups rice</li>
          <li>Dal</li>
          <li>150g chicken/paneer</li>
          <li>Vegetables</li>
        </ul>
      </div>
      <div class="meal-plan">
        <h3>Post-Workout (250 kcal, 25g protein)</h3>
        <ul>
          <li>1 scoop whey protein</li>
          <li>1 banana smoothie</li>
        </ul>
      </div>
      <div class="meal-plan">
        <h3>Dinner (550 kcal, 40g protein)</h3>
        <ul>
          <li>2 rotis</li>
          <li>Sabzi</li>
          <li>200g chicken/paneer</li>
        </ul>
      </div>
      <div class="meal-plan">
        <h3>Snack (200 kcal, 15g protein)</h3>
        <ul>
          <li>40g paneer</li>
          <li>1 glass milk</li>
        </ul>
      </div>
      <p><strong>Total: ${surplus} calories/day | Protein: ${protein}g</strong></p>
    `;
  }
  
  return `
    <div class="meal-plan">
      <h3>Balanced Plan (${maintenance} kcal/day)</h3>
      <ul>
        <li>Breakfast: Whole grain cereal + milk + fruits (400 kcal)</li>
        <li>Lunch: Balanced meal with protein, carbs, and vegetables (500 kcal)</li>
        <li>Dinner: Light meal with vegetables and lean protein (400 kcal)</li>
        <li>Snacks: Nuts or fruits (200 kcal)</li>
      </ul>
    </div>
  `;
}

// Generate Exercise Form Guide PDF content
export function generateExerciseFormGuidePDF(): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Exercise Form Guide</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; }
    h1 { color: #FF7A00; text-align: center; }
    h2 { color: #333; border-bottom: 2px solid #FF7A00; padding-bottom: 5px; }
    .exercise { margin: 20px 0; padding: 15px; background-color: #f9f9f9; border-radius: 5px; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
    ul { margin: 10px 0; }
    li { margin: 5px 0; }
  </style>
</head>
<body>
  <h1>💪 FitLine-Gym Exercise Form Guide</h1>
  
  <div class="exercise">
    <h2>Squats</h2>
    <ul>
      <li>Feet shoulder-width apart, toes slightly turned out</li>
      <li>Keep chest up and core engaged</li>
      <li>Lower down as if sitting in a chair</li>
      <li>Knees should track over toes, not cave inward</li>
      <li>Go down until thighs are parallel to floor</li>
      <li>Drive through heels to stand back up</li>
    </ul>
  </div>

  <div class="exercise">
    <h2>Push-ups</h2>
    <ul>
      <li>Start in plank position, hands slightly wider than shoulders</li>
      <li>Keep body in straight line from head to heels</li>
      <li>Lower body until chest nearly touches floor</li>
      <li>Elbows should be at 45-degree angle</li>
      <li>Push back up to starting position</li>
      <li>Keep core tight throughout movement</li>
    </ul>
  </div>

  <div class="exercise">
    <h2>Plank</h2>
    <ul>
      <li>Start in push-up position on forearms</li>
      <li>Body should form straight line</li>
      <li>Engage core and glutes</li>
      <li>Don't let hips sag or rise too high</li>
      <li>Breathe normally</li>
      <li>Hold for desired duration</li>
    </ul>
  </div>

  <div class="exercise">
    <h2>Lunges</h2>
    <ul>
      <li>Step forward with one leg</li>
      <li>Lower back knee toward ground</li>
      <li>Front knee should be over ankle, not past toes</li>
      <li>Keep torso upright</li>
      <li>Push through front heel to return</li>
      <li>Alternate legs</li>
    </ul>
  </div>

  <div class="footer">
    <p>Generated by FitLine-Gym | Always prioritize form over weight or speed</p>
    <p>If you experience pain, stop immediately and consult a professional</p>
  </div>
</body>
</html>
  `.trim();
}

// Generate Goal Setting Worksheet PDF content
export function generateGoalSettingWorksheetPDF(userProfile: UserProfile): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Goal Setting Worksheet</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; }
    h1 { color: #FF7A00; text-align: center; }
    h2 { color: #333; border-bottom: 2px solid #FF7A00; padding-bottom: 5px; }
    .section { margin: 20px 0; padding: 15px; background-color: #f9f9f9; border-radius: 5px; }
    .worksheet { background-color: white; padding: 20px; margin: 10px 0; border: 2px dashed #ccc; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <h1>🎯 FitLine-Gym Goal Setting Worksheet</h1>
  
  <div class="section">
    <h2>SMART Goals Framework</h2>
    <p><strong>S</strong>pecific | <strong>M</strong>easurable | <strong>A</strong>chievable | <strong>R</strong>elevant | <strong>T</strong>ime-bound</p>
  </div>

  <div class="worksheet">
    <h2>My Current Profile</h2>
    <p><strong>Name:</strong> ${userProfile.displayName || '_________________'}</p>
    <p><strong>Current Goal:</strong> ${userProfile.fitnessGoal || '_________________'}</p>
    <p><strong>Experience Level:</strong> ${userProfile.experienceLevel || '_________________'}</p>
  </div>

  <div class="worksheet">
    <h2>Short-term Goal (4 weeks)</h2>
    <p><strong>What do I want to achieve?</strong></p>
    <p style="min-height: 50px; border-bottom: 1px solid #ccc; margin: 10px 0;">_________________________________</p>
    <p><strong>How will I measure success?</strong></p>
    <p style="min-height: 50px; border-bottom: 1px solid #ccc; margin: 10px 0;">_________________________________</p>
    <p><strong>Target date:</strong> _________________</p>
  </div>

  <div class="worksheet">
    <h2>Long-term Goal (12 weeks)</h2>
    <p><strong>What do I want to achieve?</strong></p>
    <p style="min-height: 50px; border-bottom: 1px solid #ccc; margin: 10px 0;">_________________________________</p>
    <p><strong>How will I measure success?</strong></p>
    <p style="min-height: 50px; border-bottom: 1px solid #ccc; margin: 10px 0;">_________________________________</p>
    <p><strong>Target date:</strong> _________________</p>
  </div>

  <div class="worksheet">
    <h2>Action Plan</h2>
    <p><strong>What steps will I take?</strong></p>
    <ol>
      <li style="min-height: 30px; border-bottom: 1px solid #ccc; margin: 10px 0;">_________________________________</li>
      <li style="min-height: 30px; border-bottom: 1px solid #ccc; margin: 10px 0;">_________________________________</li>
      <li style="min-height: 30px; border-bottom: 1px solid #ccc; margin: 10px 0;">_________________________________</li>
    </ol>
  </div>

  <div class="footer">
    <p>Generated by FitLine-Gym | Review and update your goals regularly</p>
  </div>
</body>
</html>
  `.trim();
}

// Helper function to download HTML as PDF (opens print dialog)
export function downloadPDF(htmlContent: string, filename: string) {
  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
  
  // Also open in new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}

